// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAysZyzA_Wd-nwDRg3QrpDwfugfKuu7lmE',
    appId: '1:240585260102:web:68aac323b707122c15de47',
    messagingSenderId: '240585260102',
    projectId: 'scout-best-group',
    authDomain: 'scout-best-group.firebaseapp.com',
    storageBucket: 'scout-best-group.firebasestorage.app',
    measurementId: 'G-VH626L8Q86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYFuyKvo-0-ZjIzbGb9xvqen-AOEMF-XI',
    appId: '1:240585260102:android:cfb1e914e659db0115de47',
    messagingSenderId: '240585260102',
    projectId: 'scout-best-group',
    storageBucket: 'scout-best-group.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAysZyzA_Wd-nwDRg3QrpDwfugfKuu7lmE',
    appId: '1:240585260102:web:69362f9cb6b987f815de47',
    messagingSenderId: '240585260102',
    projectId: 'scout-best-group',
    authDomain: 'scout-best-group.firebaseapp.com',
    storageBucket: 'scout-best-group.firebasestorage.app',
    measurementId: 'G-FPPS689VL7',
  );
}
